version: '3'
services:
  mysql:
    hostname: mysql
    image: mysql:5.7.26
    container_name: mysql # 指定容器名称，如果不设置此参数，则由系统自动生成
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 设置utf8字符集
    environment:
      - TZ=Asia/Shanghai # 设置容器时区与宿主机保持一致
      - MYSQL_ROOT_PASSWORD=root # 设置root密码
      - MYSQL_USER=root
      - MYSQL_PASS=123456
    volumes:
      - ./mysql/data:/var/lib/mysql/data # 映射数据库保存目录到宿主机，防止数据丢失
      - ./mysql/my.cnf:/etc/mysql/my.cnf # 映射数据库配置文件
    ports:
      - "3306:3306"
  
  redis:  
    hostname: redis
    image: redis:6.0.6
    container_name: redis
    restart: always
    command: redis-server /etc/redis.conf # 启动redis命令
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis.conf
    ports:
      - "6379:6379"