server:
  port: 10086



trx:
  terminal-url: 'http://localhost:3333'
  api-url: 'https://nile.trongrid.io/v1'
  token-info:
    symbol: 'USDT'
    name: 'Tether USD'

interceptor:
  exclude:
    path: "/error/**,/v3/**,/webjars/**,/swagger-resources/**,/swagger-ui/**,/admin/user/login"


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cb_v2?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: root
    password: ^qaz123@hm!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootDemoHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
  sql:
    init:
      mode: always
      continue-on-error: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6380
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 2000
    password: dream123

#====================================mybatis-plus config===============================================
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:mapper/*.xml

